package com.pontusvision.gdpr;

/*
const records = [{name: 'Jackson Turner', street: '217 Tawny End', img: 'men_1.jpg'},
  {name: 'Megan Perry', street: '77 Burning Ramp', img: 'women_1.jpg'},
  {name: 'Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '1Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '2Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '3Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '4Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '5Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '6Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '7Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '8Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '9Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '10Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '11Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '12Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '13Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '14Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '15Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '16Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '17Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '18Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '19Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '20Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '21Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '22Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '23Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '24Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '25Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '26Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '27Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '30Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '31Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '32Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '33Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '34Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '35Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '36Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '37Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '38Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '39Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '40Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '41Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '42Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '43Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '44Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '45Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '46Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '47Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '48Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '49Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '50Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '51Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '52Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '53Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '54Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '55Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '56Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '57Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '58Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '59Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '60Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '61Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '62Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '63Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '64Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '65Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '66Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '67Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '68Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '69Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '70Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '71Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '72Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '73Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '74Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '75Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '76Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '77Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '78Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '79Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '80Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '81Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '82Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '83Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '84Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '85Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '86Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '87Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '88Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '89Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '90Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '91Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '92Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '93Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '94Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '95Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '96Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '97Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '98Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '99Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '100Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '101Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '102Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '103Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '104Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '105Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '106Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '107Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '108Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '109Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '110Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '111Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '112Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '113Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '114Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '115Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '116Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '117Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '118Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '119Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '120Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '121Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '122Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '123Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '124Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '125Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '126Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '127Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '128Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: '129Ryan Harris', street: '12 Hazy Apple Route', img: 'men_2.jpg'},
  {name: 'Jennifer Edwards', street: '33 Maple Drive', img: 'women_2.jpg'},
  {name: 'Noah Jenkins', street: '423 Indian Pond Cape', img: 'men_3.jpg'}
];
 */

//import com.google.gson.Gson;
//import com.google.gson.GsonBuilder;
//import com.google.gson.JsonElement;
//import com.google.gson.JsonObject;
import org.json.JSONObject;

import java.util.Map;

public class Record extends JSONObject
{

  public Record()
  {
    super();
  }

  public Record(Map<? extends String, ? extends String> m)
  {
    super(m);
  }
}
