name: Patch n Push

on:
  push:
    branches: [ master ]

jobs:

  push-dockerhub:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-multi-buildx

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          install: true

          

      - name: semver-tags
        id: semver-tags
        uses: SOLIDSoftworks/semver-tags@1.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag-prefix: 'v'
          default-version: '1.13.2'

      - name: envsubst Dockerfile
        run: |
          export DOLLAR='$'
          export TAG=${{ steps.semver-tags.outputs.semantic-version }}
          cat ./docker-lib/Dockerfile.template | envsubst > ./docker-lib/Dockerfile
#          cat ./docker-conf/Dockerfile.template | envsubst > ./docker-conf/Dockerfile
          cat ./docker-pontus-track-graphdb-base/base/Dockerfile.template | envsubst > ./docker-pontus-track-graphdb-base/base/Dockerfile
          cat ./docker-pontus-track-graphdb-base/orientdb/Dockerfile.template | envsubst > ./docker-pontus-track-graphdb-base/orientdb/Dockerfile
          cat ./docker-pontus-track-graphdb-base/orientdb-pt/Dockerfile.template | envsubst > ./docker-pontus-track-graphdb-base/orientdb-pt/Dockerfile

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish pontus-graphdb-odb-lib to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: pontusvisiongdpr/pontus-graphdb-odb-lib:${{ steps.semver-tags.outputs.semantic-version }}
          file: ./docker-lib/Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
          push: true

      - name: Publish pontus-graphdb-odb-conf to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: pontusvisiongdpr/pontus-graphdb-odb-conf:${{ steps.semver-tags.outputs.semantic-version }}
          file: ./docker-lib/Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
          push: true

      - name: Publish pontus-track-graphdb-base to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: ./docker-pontus-track-graphdb-base/base
          tags: pontusvisiongdpr/pontus-track-graphdb-base:${{ steps.semver-tags.outputs.semantic-version }}
          # file: ./docker-lib/Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
          push: true

      - name: Publish pontus-track-graphdb-odb to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: ./docker-pontus-track-graphdb-base/orientdb
          tags: pontusvisiongdpr/pontus-track-graphdb-odb:${{ steps.semver-tags.outputs.semantic-version }}
          # file: ./docker-lib/Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
          push: true

      - name: Publish pontus-track-graphdb-odb-pt to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: ./docker-pontus-track-graphdb-base/orientdb-pt
          tags: pontusvisiongdpr/pontus-track-graphdb-odb-pt:${{ steps.semver-tags.outputs.semantic-version }}
          # file: ./docker-lib/Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
          push: true
