# STEP 3: AFTER push it to DockerHub (gonna need Docker Credentials as GitHub secret)

name: Push Image to DockerHub

on:
  push:
    branches: [ master ]

jobs:
  push-dockerhub:

        runs-on: ubuntu-latest
        
        steps:
          - uses: actions/checkout@v2

          - name: Docker Push Action
            uses: mr-smithers-excellent/docker-build-push@v5.6
            with:
              image: pontusvisiongdpr/pontus-track-graphdb-odb-pt:latest
#              tags: latest
              registry: docker.io
#              dockerfile: Dockerfile.ci
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
#      publish:
#        needs: build
